name: Deploy MkDocs

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install MkDocs and Required Plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-awesome-pages-plugin

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
